version: '3.8'
 
services:
 
  web:
    image: env-web:latest
    container_name: nodejs
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    volumes:
      # 1. 自身のプロジェクト本体
      - ./vol/nodejs:/home/node/projects
      # 2. ★★★ 画像読み込み用パス修正（ホスト側のパスに /images を追加）★★★
      # C:\docker_data\images の中身を、DBのパス /images にマウント
      - C:/docker_data/images:/images
 
  web2:
    image: env-web:latest
    container_name: nodejs2
    tty: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "4000:4000"
    volumes:
      # 1. 自身のプロジェクト本体
      - ./vol/nodejs2:/home/node/projects
 
      # 2. ★★★ 画像書き込み用パス修正（ホスト側のパスに /images を追加）★★★
      # C:\docker_data\images の中身を、web2コンテナの /app_images にマウント
      - C:/docker_data/images:/app_images
 
  db:
    image: env-db:latest
    container_name: mysql
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - "3306:3306"
    volumes:
      - ./vol/mysql:/var/lib/mysql